name: Check Markdown links

on:
  push:
    paths:
      - docs/**
    branches:
      - 'main'
  pull_request:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: '.github/workflows/check-md-link-config.json'
        folder-path: 'docs'
